{
 "title": "story-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(cometbft_consensus_height, chain_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cometbft_consensus_height{chain_id=\"$chain_id\"}, instance)"
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average block time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", instance=\"$instance\" , job=\"$job\"}/cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Token staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Validator set updates",
   "type": "stat",
   "description": "Number of validator set updates returned by the application since process start.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_state_validator_set_updates{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block size bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Minted tokens",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "cosmos_minted_tokens{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators overview",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Chain voting power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "$instance overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Story version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lib_buildinfo_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Commit version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lib_buildinfo_git_commit", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Catching up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  }
 ]
}